imports:
  - $from pathlib import Path

workspace: $Path('/home/jackzhy/IROS_2024/dVRK-segmentation-models')
data_dir: $Path('/home/jackzhy/IROS_2024/dVRK-segmentation-models/monai_data/rec03_dataset/rec03_dataset')

ambf_train_config:
  data_dir: $@data_dir
  train_dir_list: $[@data_dir / "train"]
  val_dir_list: $[@data_dir / "valid"]
  pretrained_weights_path: $@workspace / 'assets/weights/pretrained-weights'
  training_output_path: $@workspace / 'assets/weights/real_dvrk_weights_d1'
  mapping_file: $@data_dir / "dataset_config.yaml"
  device: "cuda"
  epochs: 20
  learning_rate: $float("1e-3")

test:
  _requires_: "@create_test_dir"
  root: $Path('/home/jackzhy/dVRK-segmentation-models/assets/weights')
  weights: $@test#root / 'real_dvrk_weights_d1/myweights.pt'
  # weights: $@test#root / 'myweights_realdvrk_d1_v0.0/myweights.pt'
  predictions_dir: $@ambf_train_config#data_dir / 'predictions'

create_test_dir:
  - $print('creating test dir...')
  - $@test#predictions_dir.mkdir(parents=True, exist_ok=True)

check_paths:
  - $print("train_dir exists:", @ambf_train_config#train_dir_list[0].exists())
  - $print("valid exists:", @ambf_train_config#val_dir_list[0].exists())
