imports:
  - $from pathlib import Path

workspace: $Path('/home/jackzhy/IROS_2024/dVRK-segmentation-models')
data_dir: $Path('/home/jackzhy/IROS_2024/dVRK-segmentation-models/monai_data/AMBF_DATASETS/')
annotations_type: "5colors"

ambf_train_config:
  annotations_type: $@annotations_type
  data_dir: $@data_dir
  train_dir_list: $[@data_dir / "000001", @data_dir / "000003", @data_dir / "000004", @data_dir / "000005"]
  val_dir_list: $[@data_dir / "000002"]
  pretrained_weights_path: $@workspace / 'assets/weights/pretrained-weights'
  training_output_path: $@workspace / 'assets/weights/myweights_jack_0306'
  mapping_file: $@data_dir / "mapping.json"
  device: "cuda"
  epochs: 500
  learning_rate: $float("1e-5")
