defaults:
  - path_config: juanthin7_newtool
  - _self_

hydra:
  run:
    dir: ./outputs/${hydra.job.config_name}/logs/${now:%Y%m%d}_${now:%H%M%S}

global_device: "cuda"

path_config:
  workspace: ???
  data_dir: ???
  pretrained_weights_path: ???
  training_output_path: ???
  mapping_file: ???
  weights_file: ???
  predictions_path: ???

train_config:
  device: "${..global_device}"
  epochs: 20
  batch_size: 8
  num_workers: 4
  learning_rate: 1e-4
  pretrained_weights_path: "${..path_config.pretrained_weights_path}"
  training_output_path: "${..path_config.training_output_path}"

test_config:
  device: "${..global_device}"
  batch_size: 1
  num_workers: ${..train_config.num_workers}
  weights_file: ${..path_config.trained_weights_file_path}/${..path_config.trained_weights_file_name}
  predictions_dir: "${..path_config.predictions_path}"

actions:
  show_images: true
  train: true
  test: true
  save_test_predictions: true
  calculate_metrics: false
