imports:
  - $from pathlib import Path

workspace: $Path('/home/jbarrag3/research_juan/dVRK-segmentation-models')
data_dir: $Path('/home/jbarrag3/research_juan/data/dVRK_datasets/Dataset1_rec03')

ambf_train_config:
  data_dir: $@data_dir
  train_dir_list: $[@data_dir / "train"]
  val_dir_list: $[@data_dir / "valid"]
  pretrained_weights_path: $@workspace / 'assets/weights/pretrained-weights'
  training_output_path: $@workspace / 'assets/weights/myweights_realdvrk_d1_v0.1'
  mapping_file: $@data_dir / "dataset_config.yaml"
  device: "cuda"
  epochs: 200 
  learning_rate: $float("0.6e-3")

check_paths:
  - $print("workspace dir exists:", @workspace.exists())
  - $print("train_dir exists:", @ambf_train_config#train_dir_list[0].exists())
  - $print("valid exists:", @ambf_train_config#val_dir_list[0].exists())
