defaults:
  - path_config: juanubuntu
  - _self_

global_device: "cuda"

path_config:
  workspace: ???
  data_dir: ???
  pretrained_weights_path: ???
  training_output_path: ???
  mapping_file: ???
  weights_file: ???
  predictions_path: ???

train_config:
  device: "${..global_device}"
  epochs: 2
  batch_size: 8
  num_workers: 4
  learning_rate: 1e-3
  pretrained_weights_path: "${..path_config.pretrained_weights_path}"
  training_output_path: "${..path_config.training_output_path}"

test_config:
  device: "${..global_device}"
  batch_size: 1
  num_workers: ${..train_config.num_workers}
  weights_file: "${..path_config.weights_file}"
  predictions_dir: "${..path_config.predictions_path}"

actions:
  show_images: false
  train: false
  show_inferences: false
  calculate_metrics: true
