# global workspace
workspace: "/home/juan1995/research_juan/accelnet_grant/dVRK-segmentation-models"
data_dir: "/home/juan1995/research_juan/accelnet_grant/sim2real/data"
# dataset paths
train_data_path: "${.data_dir}/pilotdata_01_train"
test_data_path: "${.data_dir}/pilotdata_02_test"
mapping_file: "${.train_data_path}/phantom_segmentation.yaml"
# training paths
pretrained_weights_path: "${.workspace}/assets/weights/pretrained-weights"
training_output_path: "${.workspace}/assets/weights/segmented-weights"
weights_file: "myweights.pt" 
trained_weights_path: "${.training_output_path}/${.weights_file}"
predictions_path: .
