# global workspace
workspace: "/home/juan1995/research_juan/accelnet_grant/dVRK-segmentation-models"
data_dir: "/home/juan1995/research_juan/accelnet_grant/sim2real/data"
# dataset paths
train_data_path: "${.data_dir}/pilotdata_01_train"
test_data_path: "${.data_dir}/pilotdata_02_test"
mapping_file_name: seg_meta_phantom.yaml
mapping_file_path: "${.train_data_path}/${.mapping_file_name}"
# training paths
pretrained_weights_path: "${.workspace}/assets/weights/pretrained-weights"
training_output_path: ${hydra:runtime.output_dir}/../../
trained_weights_file_name: myweights.pt
trained_weights_file_path: "${.training_output_path}/weights/"
predictions_path: .
